[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[dev]
  command = "npm run develop"



[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/"
  to = "/welcome"
  force=true
  status = 301
